server:
  port: 8082

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/microservice
    password: postgres
  application:
    name: HOTEL-SERVICE
  jpa:
    hibernate:
      ddl-auto: update

  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true

#okta config
okta:
  oauth2:
    issuer: https://dev-61848187.okta.com/oauth2/default
    audience: api://default


